services:
  db:
    image: mongo:7
    container_name: formotex-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-example}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-formotex}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formotex-api
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://root:example@db:27017/formotex?authSource=admin}
      - JWT_SECRET=${JWT_SECRET:-change_me}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS:-10}
    ports:
      - "4000:4000"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:

